name: Auto Merge on Successful CI

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

permissions:
  pull-requests: write
  contents: write

jobs:
  enable-auto-merge:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
    steps:
      - name: Get PR number
        id: pr
        run: |
          # Extract PR number from workflow run
          PR_NUMBER=$(echo '${{ toJson(github.event.workflow_run.pull_requests) }}' | jq -r '.[0].number // empty')
          if [ -z "$PR_NUMBER" ]; then
            echo "No PR associated with this workflow run"
            exit 0
          fi
          echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT

      - name: Enable auto-merge
        if: steps.pr.outputs.pr_number
        run: |
          gh pr merge ${{ steps.pr.outputs.pr_number }} \
            --auto \
            --squash \
            --delete-branch \
            --repo ${{ github.repository }} \
            || echo "Auto-merge may already be enabled or PR not ready"